name: 'git spare checkout'
description: 'git sparse checkout'
author: 'raisen'

inputs:
  files:
    description: 'Files to checkout from the repo'
    required: true
  token:
    description: 'A Github Private Access Token'
    required: true
  branch:
    description: 'Branch to checkout files from'
    required: false
    default: master
  user:
    description: 'username who owns the personal access token'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        echo ${{ inputs.token }}
        echo ${GITHUB_REPOSITORY}
        mkdir git
        REPO="https://${{ inputs.user }}:${{ inputs.token }}@github.com/${GITHUB_REPOSITORY}.git"
        git clone --filter=blob:none --no-checkout --sparse $REPO git
        cd git
        git sparse-checkout init --cone
        while IFS= read -r line; do
          fname=$(echo "$line" | xargs echo -n)
          git sparse-checkout add "$fname"
        done <<< "${{ inputs.files }}"
        git sparse-checkout add ${{ inputs.files }}
        git checkout ${{ inputs.branch }}
        shopt -s dotglob
        mv * ..
        cd ..
        rm -rf git
      shell: bash
